### ISSUE TITLE
JSON API support?

### ISSUE THREAD

**Issue by Korijn** [vortico/flama#20]
Hi, I'm investigating the feasibility of implementing the [JSON API specification](https://jsonapi.org/) with Flama.

It's probably easy to add a JSON API codec to Flama using [marshmallow-jsonapi](https://github.com/marshmallow-code/marshmallow-jsonapi).

The other parts, like which status codes to return and what query parameters should look like, are possibly harder to achieve without messing with Flama internals.

Would you agree with this quick assessment or do you think it would be easier than I'm currently thinking?

**Comment by Korijn** [comment]
Looking at this some more, it probably already matches quite closely and is more about extending flama to handle the "filter", " paginate" and "side-loading" features for the List endpoint according to the spec.

**Comment by perdy** [comment]
> Looking at this some more, it probably already matches quite closely and is more about extending flama to handle the "filter", " paginate" and "side-loading" features for the List endpoint according to the spec.

I agree on that, but I see it more like an optional feature over `Resources`. The bad side about using `marshmallow-jsonapi` is that [isn't compatible with `apispec`](https://github.com/marshmallow-code/marshmallow-jsonapi/issues/12) so the schema and docs generation must be disabled for using it.

I would say that a side library extending Flama's Resources could be a good starting point.

**Comment by migduroli** [comment]
@perdy, I'm closing this issue. I'm afraid the current state of the project is no longer compatible with these changes. Indeed, this might've been resolved indirectly via other changes that have come up over the last few months for the release of versions `>=1.0.0`. Thus, we're closing the issue, and will re-consider whether this is still needed in the framework over a discussion prior to any work. This way we can ensure we are note duplicating efforts. And, for sure, thanks a lot to @Korijn for this and any future suggestions :)
